# SPDX-FileCopyrightText: 2025 Matthew Taylor <taylormw163@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

#:schema https://reuse.software/reuse-toml-v1.schema.json

version = 1

[[annotations]]
path = [
    "workflows/**/*.yml",
    "ISSUE_TEMPLATE/**/*.yml",
]
SPDX-FileCopyrightText = "2025 Matthew Taylor <taylormw163@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"
