# Workflow to publish a new binary release.
# Triggered whenever code-quality.yml succeeds on a push to a tag branch.
name: Release
on:
  push:
    tags:
      - v*
  workflow_dispatch:


permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  code-quality:
    name: Verify Code Quality
    uses: ./.github/workflows/code-quality.yml

  release:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          # Needed for tags to exist locally
          fetch-depth: 0
          fetch-tags: true

      - name: Create GitHub CLI extension
        uses: cli/gh-extension-precompile@v2
        with:
          generate_attestations: true
          go_version_file: go.mod
          go_build_options: >
            -ldflags="-X 'github.com/Bertie690/gh-pr-list/cli.version=${{ github.ref_name }}'
            -X 'github.com/Bertie690/gh-pr-list/cli.commit=${{ github.sha }}'"
            -X 'github.com/Bertie690/gh-pr-list/cli.buildTime=$(date --utc '+%a, %d %b %Y %T %Z')'"
