# Workflow to publish a new binary release.
# Triggered whenever code-quality.yml succeeds on a push to a tag branch.
name: release
on:
  workflow_run:
    workflows: ["Code Quality"]
    types: completed

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    # Only run if:
    # 1. The triggering workflow succeeded
    # 2. It was run on a tag (refs/tags/…)
    if: ${{ startsWith(github.ref, "refs/tags/") && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          # Needed for tags to exist locally
          fetch-depth: 0
          fetch-tags: true

      - name: Create GitHub CLI extension
        uses: cli/gh-extension-precompile@v2
        with:
          generate_attestations: true
          go_version_file: go.mod
          # TODO: Uncomment once https://github.com/cli/gh-extension-precompile/issues/70 is fixed
          # go_build_options: >
          #   -ldflags="-X 'github.com/Bertie690/gh-pr-list/cli.version=${{ github.ref_name }}'
          #   -X 'github.com/Bertie690/gh-pr-list/cli.commit=${{ github.sha }}'"
          #   -X 'github.com/Bertie690/gh-pr-list/cli.buildTime=$(date --utc '+%a, %d %b %Y %T %Z')'"

