# Workflow to publish a new release.
# Triggered whenever tests.yml succeeds on a push to a tag branch.
name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The numerical version of the tag to cut, either with or without the starting v prefix."
        required: true
        type: number

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cli/gh-extension-precompile@v2
        with:
          generate_attestations: true
          go_version_file: go.mod
