# Workflow to publish a new binary release.
# Triggered whenever code-quality.yml succeeds on a push to a tag branch.
name: release
on:
  workflow_run:
    workflows: ["Code Quality"]
    types: completed

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    # Only run if:
    # 1. The triggering workflow succeeded
    # 2. It was run on a tag (refs/tags/…)
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          startsWith(github.event.workflow_run.head_branch, 'refs/tags/') }}

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          # Needed for tags to exist locally
          fetch-depth: 0
          fetch-tags: true

      - name: Capture current date/time
        run: |
          {
            echo 'TIME<<EOF'
            LC_ALL=C TZ=GMT date '+%a, %d %b %Y %T %Z'
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Test stored timestamp works
        run: >
          echo "Deploying at $TIME"

      - name: Create GitHub CLI extension
        uses: cli/gh-extension-precompile@v2
        with:
          generate_attestations: true
          go_version_file: go.mod
          go_build_options: >
            -ldflags="
            -X 'github.com/Bertie690/gh-pr-list/cli.version=${{ github.action_ref }}'
            -X 'github.com/Bertie690/gh-pr-list/cli.commit=${{ github.sha }}'
            -X 'github.com/Bertie690/gh-pr-list/cli.buildTime=$TIME'"
