# Workflow to perform code quality checks on each commit/PR to main or a tag
name: Code Quality
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - "main"

  push:
    branches:
      - "main"
    tags:
      - "v*"
  workflow_dispatch: # allow manually triggering on drafts if need be

env:
  go-version: 1.25.x

jobs:
  test:
    # don't run job on draft PRs unless manually triggered
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # build & test
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}
          check-latest: true
          cache: true

      - name: Setup Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true

      - name: Test Go Files
        id: go-tests
        run: mage test ""

      - name: Upload gotestsum reports
        uses: actions/upload-artifact@v4
        with:
          name: gotestsum-report
          path: |
            tmp/diff.jsonl
            tmp/test-results/*
          overwrite: true
          retention-days: 7
        if: always()

      - name: Produce Test Summary
        uses: test-summary/action@v2
        with:
          paths: "tmp/**/*-report.xml"
        if: always()
  release:
    needs: ["test"]
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    run: gh workflow run --ref ${{ github.ref_name }} Sonar
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
